# This file contains the configurations for the event-based eye tracking pipeline.
defaults:
  logroot: logs
  logdir: ''
  expname: 'dummy'
  seed: 0
  log_video_render: True # log the render of the envs
  replicas: 1
  save_stats_str: True # whether to save the JIT stats string to a file

  logger:
    outputs: [jsonl, tensorboard]
    filter: 'score|length|fps|ratio|train/loss/|train/rand/'
    timer: True
    fps: 15
    user: ''

  jax:
    platform: cuda
    compute_dtype: bfloat16 # float32 # bfloat16
    prealloc: True
    jit: True
    debug: False
    enable_policy: True
    compile: True
    profiler: False
    gpuflags: True

  run:
    steps: 100000 # training steps
    eval_steps: 1e4 # 10k steps
    log_every: 15 # 10 seconds
    report_every: 30 # 5 minutes
    save_every: 100 # 100 seconds
    report_batches: 1 # number of batches to take to do reports
    from_checkpoint: ''
    actor_addr: 'localhost:{auto}'
    replay_addr: 'localhost:{auto}'
    logger_addr: 'localhost:{auto}'
    actor_batch: -1
    actor_threads: 1
    agent_process: False
    remote_replay: False
    remote_envs: False
    usage: {psutil: True, nvsmi: True, gputil: False, malloc: False, gc: False}
    debug: True # for using parallel environments (False) or not (True)

  task: threeet # NOTE: This has to be a list of different dataset because we want to train on multiple dataset, but for now, we only have one dataset
  env:
    threeet: { datadir: 'data/event-based-eye-tracking-ais2024', event_transform: eventframe, image_size: [640, 480] }
    eveye: { datadir: 'data/eveye', event_transform: eventframe, image_size: [640, 480] }

  # Related environmental and logging setup
  n_envs: 4
  batch_size: 64 # number of samples per batch
  batch_length: 32 # number of steps to take per batch
  report_length: 16
  replay_context: 1 # number of steps to look back for replay
  consec_train: 1 # number of batches to train per step
  consec_report: 1
  report: True

  # Replay
  replay:
    size: 100000 # 100000 is enough
    online: True
    fracs: {uniform: 1.0, priority: 0.0, recency: 0.0}
    prio: {exponent: 0.8, maxfrac: 0.5, initial: inf, zero_on_sample: True}
    priosignal: model
    recexp: 1.0
    chunksize: 1024

  # Agent Setup
  agent: dummy

  # Model and Networks Setup
  encoder:
    prockeys: '.*'
    cnn: {depth: 16, mults: [2, 3, 3, 4, 4, 4, 4], layers: 1, units: 16, act: silu,
      norm: layer, winit: trunc_normal_in, symlog: True, outer: False, kernel: 5, strided: True}
    cbconvlstm: {depth: 16, mults: [2, 3, 3, 4, 4, 4, 4], layers: 1, units: 16, act: silu,
      norm: layer, winit: trunc_normal_in, symlog: True, outer: False, kernel: 5, strided: True}

  dynamics:
    mlp: {space: 64, dist: 'normal_logstd', units: 64, layers: 2, act: silu, bias: True, winit: trunc_normal, binit: zeros, norm: rms} # a single mlp with output distribution
    gru: {units: 64, bias: True, winit: trunc_normal, binit: zeros, norm: rms, update_bias: -1.0}
    mamba: {deter: 16, units: 64, kernel: 4, expand: 16, bias: True, winit: trunc_normal, binit: zeros}
    rssm: {deter: 128, hidden: 64, stoch: 16, classes: 16, norm: rms, act: silu, unroll: False, unimix: 0.01, outscale: 1.0, imglayers: 3, obslayers: 3, dynlayers: 3, absolute: False, blocks: 8, free_nats: 1.0}
    ais2m: {deter: 128, hidden: 64, stoch: 16, classes: 16, norm: rms, act: silu, unroll: False, unimix: 0.01, outscale: 1.0, imglayers: 3, obslayers: 3, dynlayers: 3, alphalayers: 3, absolute: False, blocks: 8, free_nats: 1.0}
    ais3m: {deter: 128, hidden: 64, stoch: 16, classes: 16, norm: rms, act: silu, unroll: False, unimix: 0.01, outscale: 1.0, imglayers: 3, obslayers: 3, dynlayers: 3, alphalayers: 3, absolute: False, blocks: 8, free_nats: 1.0}
    lif: {beta: 0.9, learnable_beta: True, threshold: 1.0, learnable_threshold: True, spike_grad: sigmoid, reset_mechanism: subtract,
      graded_spikes_factor: 1.0, learnable_graded_spikes_factor: True}
    projector: {units: 128, bias: False, winit: trunc_normal, binit: zeros}

  decoder:
    prockeys: '.*'
    cnn: {units: 64, norm: rms, act: silu, outscale: 1.0, depth: 64,
      mults: [2, 3, 3, 4, 4, 4, 4], layers: 3, kernel: 5, symlog: True,
      bspace: 8, outer: False, strided: False, bias: True, winit: trunc_normal, binit: zeros}

  head:
    general: {units: 64, layers: 2, act: silu, norm: layer, minstd: 1.0, maxstd: 1.0, unimix: 0.0,
      bins: 255, outscale: 1.0, bias: True, winit: trunc_normal, binit: zeros}
    # snr: {units: 64, layers: 2, act: silu, norm: layer, minstd: 1.0, maxstd: 1.0, unimix: 0.0,
    #   bins: 255, outscale: 1.0, bias: True, winit: trunc_normal, binit: zeros}

  # Optimizer configs
  opt: {lr: 6e-5, agc: 0.3, eps: 1e-20, beta1: 0.9, beta2: 0.999, nesterov: False, wd: 0.0, wdregex: r'/kernel$', schedule: const, warmup: 1000, anneal: 0}

  # Configurations of various hyperparameters
  loss_scales: {dyn: 1.0, rep: 1.0, alpha: 1.0}
  # snr_box_size: [80, 40] # Width, Height
  # default_alpha: 0.5
  confidence:
    roi_size: [70, 40] # Width, Height of the region of interest around the pupil center
    event_threshold: 0.0 # Threshold for significant events in RAW data
    default_alpha: 0.5 # Default alpha for frames with invalid pupil labels
    event_coverage_ratio_threshold: 0.1 # Minimum coverage ratio to consider signal valid
    weights: {quality: 0.0001, coverage: 0.9999} # Weights for combining event density and coverage ratio


#============================ Environment Primitives ======================
3et_80x60:
  task: threeet
  env.threeet.datadir: 'data/event-based-eye-tracking-ais2024'
  env.threeet.image_size: [80, 60]
  .*\.mults: [2, 3, 3, 4]
  encoder.prockeys: 'frame'
  decoder.prockeys: 'frame'


3et_160x120:
  task: threeet
  env.threeet.datadir: 'data/event-based-eye-tracking-ais2024'
  env.threeet.image_size: [160, 120]
  .*\.mults: [2, 3, 3, 4, 4]
  encoder.prockeys: 'frame'
  decoder.prockeys: 'frame'
3et: # shortcut for 160x120
  task: threeet
  env.threeet.datadir: 'data/event-based-eye-tracking-ais2024'
  env.threeet.image_size: [160, 120]
  .*\.mults: [2, 3, 3, 4, 4]
  encoder.prockeys: 'frame'
  decoder.prockeys: 'frame'

# 3et_640x480:
#   task: threeet
#   env.threeet.datadir: 'data/event-based-eye-tracking-ais2024'
#   env.threeet.image_size: [640, 480]
#   .*\.mults: [2, 3, 3, 4, 4, 4, 4]
#   encoder.prockeys: 'frame'
#   decoder.prockeys: 'frame'


eveye_80x60:
  task: eveye
  env.eveye.datadir: 'data/eveye'
  env.eveye.image_size: [80, 60]
  .*\.mults: [2, 3, 3, 4]
  encoder.prockeys: 'frame'
  decoder.prockeys: 'frame'


eveye_160x120:
  task: eveye
  env.eveye.datadir: 'data/eveye'
  env.eveye.image_size: [160, 120]
  .*\.mults: [2, 3, 3, 4, 4]
  encoder.prockeys: 'frame'
  decoder.prockeys: 'frame'
eveye: # shortcut for 160x120
  task: eveye
  env.eveye.datadir: 'data/eveye'
  env.eveye.image_size: [160, 120]
  .*\.mults: [2, 3, 3, 4, 4]
  encoder.prockeys: 'frame'
  decoder.prockeys: 'frame'

#============================ Agent Primitives ============================

### 500k
cnn_500k: &cnn_500k
  agent: cnn
  .*\.units: 32
  .*\.depth: 20
  .*\.layers: 4

cnngru_500k: &cnngru_500k
  agent: cnngru
  .*\.units: 32
  .*\.depth: 16
  .*\.layers: 4

cnnsnn_500k: &cnnsnn_500k
  agent: cnnsnn
  .*\.units: 32
  .*\.depth: 16
  .*\.layers: 4

cnnbigru_500k: &cnnbigru_500k
  agent: cnnbigru
  .*\.units: 16
  .*\.depth: 16
  .*\.layers: 2

cbconvlstm_500k: &cbconvlstm_500k
  agent: cbconvlstm
  .*\.units: 8
  .*\.depth: 8
  .*\.layers: 2

mamba_500k: &mamba_500k
  agent: mamba
  .*\.units: 16
  .*\.deter: 16
  .*\.depth: 16
  .*\.expand: 8
  .*\.layers: 2

mambapupil_500k: &mambapupil_500k
  agent: mambapupil
  .*\.units: 16
  .*\.deter: 16
  .*\.depth: 16
  .*\.expand: 8
  .*\.layers: 2

custom_500k: &custom_500k
  agent: custom
  .*\.units: 32
  .*\.depth: 16
  .*\.layers: 4
  .*\.deter: 32
  .*\.stoch: 16
  .*\.classes: 16

custom2_500k: &custom2_500k
  agent: custom2
  .*\.units: 32
  .*\.depth: 16
  .*\.layers: 4
  .*\.deter: 128
  .*\.stoch: 32
  .*\.classes: 16

custom2snn_500k: &custom2snn_500k
  agent: custom2snn
  .*\.units: 32
  .*\.depth: 16
  .*\.layers: 4
  .*\.deter: 128
  .*\.stoch: 32
  .*\.classes: 16


### 2m

cnn_2m: &cnn_2m
  agent: cnn
  .*\.units: 64
  .*\.depth: 64
  .*\.layers: 8

cnngru_2m: &cnngru_2m
  agent: cnngru
  .*\.units: 32
  .*\.depth: 32
  .*\.layers: 4

cnnbigru_2m: &cnnbigru_2m
  agent: cnnbigru
  .*\.units: 32
  .*\.depth: 32
  .*\.layers: 4

cbconvlstm_2m: &cbconvlstm_2m
  agent: cbconvlstm
  .*\.units: 32
  .*\.depth: 32
  .*\.layers: 4

mamba_2m: &mamba_2m
  agent: mamba
  .*\.units: 32
  .*\.deter: 32
  .*\.depth: 32
  .*\.expand: 32
  .*\.layers: 4

mambapupil_2m: &mambapupil_2m
  agent: mambapupil
  .*\.units: 32
  .*\.deter: 32
  .*\.depth: 32
  .*\.expand: 32
  .*\.layers: 4


## 10m

cnn_10m: &cnn_10m
  agent: cnn
  .*\.units: 128
  .*\.depth: 64
  .*\.layers: 6

cnngru_10m: &cnngru_10m
  agent: cnngru
  .*\.units: 128
  .*\.depth: 64
  .*\.layers: 8

cnnbigru_10m: &cnnbigru_10m
  agent: cnnbigru
  .*\.units: 128
  .*\.depth: 64
  .*\.layers: 8

cbconvlstm_10m: &cbconvlstm_10m
  agent: cbconvlstm
  .*\.units: 64
  .*\.depth: 32
  .*\.layers: 8

mamba_10m: &mamba_10m
  agent: mamba
  .*\.units: 128
  .*\.deter: 32
  .*\.depth: 64
  .*\.expand: 16
  .*\.layers: 4

mambapupil_10m: &mambapupil_10m
  agent: mambapupil
  .*\.units: 128
  .*\.deter: 32
  .*\.depth: 64
  .*\.expand: 16
  .*\.layers: 4


# ========================= Event transform Primitives =========================

et_eventframe:
  env.*\.event_transform: eventframe

et_binary:
  env.*\.event_transform: binary

et_binarep:
  env.*\.event_transform: binarep

et_histogram:
  env.*\.event_transform: histogram

et_voxelgrid:
  env.*\.event_transform: voxelgrid



#============================ Other Primitives ============================

jax_debug:
  run.log_every: 5 # in seconds
  # run.save_every: -1
  # run.val_every: 50 # evaluation every training step
  # run.val_ratio: 0.01 # number batch in the val dataset to evaluate, if temporary validation set counter > 1/n len val set, end validation
  # run.from_checkpoint: ''
  # <<: *size2m
  jax.jit: False
  jax.compile: False
  jax.debug: True
  run.debug: True
